Make it possible to run the RSPM image as a non-root user.
The official Ubuntu packages for RSPM set up an 'rstudio-pm' user to run
the service. However, the existing Docker image could not be run as this
user for two reasons:

* The existing Dockerfile creates some directories required at runtime
  as root; and

* The existing installation step does not use userspace license
  activation [0], so later attempts to activate a license as a non-root
  user will fail.

This commit fixes both these issues. Images still default to running as
root (for now, to preserve compatibility), but they can also be run as
'rstudio-pm' now as well.

[0]: https://docs.rstudio.com/rspm/admin/appendix/minimal-root-use-installation/#licensing

Signed-off-by: Aaron Jacobs <aaron.jacobs@rstudio.com>

diff --git a/package-manager/Dockerfile b/package-manager/Dockerfile
--- a/package-manager/Dockerfile
+++ b/package-manager/Dockerfile
@@ -19,7 +19,6 @@ RUN apt-get update --fix-missing \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 
-RUN mkdir -p /var/run/rstudio-pm
 ENV PATH /opt/rstudio-pm/bin:$PATH
 
 # Runtime settings ------------------------------------------------------------#
@@ -38,7 +37,7 @@ ARG RSPM_VERSION=2021.12.0-3
 ARG RSPM_DOWNLOAD_URL=https://cdn.rstudio.com/package-manager/ubuntu/amd64
 RUN apt-get update --fix-missing \
     && curl -O ${RSPM_DOWNLOAD_URL}/rstudio-pm_${RSPM_VERSION}_amd64.deb \
-    && gdebi -n rstudio-pm_${RSPM_VERSION}_amd64.deb \
+    && RSTUDIO_INSTALL_NO_LICENSE_INITIALIZATION=1 gdebi -n rstudio-pm_${RSPM_VERSION}_amd64.deb \
     && rm rstudio-pm_${RSPM_VERSION}_amd64.deb \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
@@ -47,7 +46,21 @@ RUN apt-get update --fix-missing \
 ENV RSPM_LICENSE ""
 ENV RSPM_LICENSE_SERVER ""
 COPY rstudio-pm.gcfg /etc/rstudio-pm/rstudio-pm.gcfg
-VOLUME ["/data"]
+
+# These directories must be owned by rstudio-pm:rstudio-pm for a container to
+# work correctly when run as this user. (The container can also be run as root,
+# which will have access to these directories anyway.)
+RUN mkdir -p /var/run/rstudio-pm /data/launcher_internal \
+    && chown rstudio-pm:rstudio-pm /var/run/rstudio-pm \
+    && chown -R rstudio-pm:rstudio-pm /data
+
+# Set up licensing to work in userspace mode. This will not prevent activating a
+# license as root, but it is required to activate one as the non-root user at
+# runtime. It's possible for this to fail and the trail will be considered over,
+# in which case we can ignore it anyway.
+USER rstudio-pm
+RUN license-manager initialize --userspace || true
+USER root
 
 ENTRYPOINT ["tini", "--"]
 CMD ["/usr/local/bin/startup.sh"]
